// <auto-generated />
using Lab0.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab0.Migrations
{
    [DbContext(typeof(AddDbContext))]
    [Migration("20251118151143_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Lab0.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "adam@wsei.edu.pl",
                            Name = "Adam"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ewa@wsei.edu.pl",
                            Name = "Ewa"
                        },
                        new
                        {
                            Id = 3,
                            Email = "karol@wsei.edu.pl",
                            Name = "Karol"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
